class Head:
    Name = ''
    Type = ''
    Price = ''
    Weight = ''
    Energy_Drain = ''
    Armor_Points = ''
    Shell_Defense = ''
    Energy_Defense = ''
    Computer_Type = ''
    Map_Type = ''
    Noise_Canceller = ''
    Bio_Sensor = ''
    Radar_Function = ''
    Radar_Range = ''
    Radar_Type = ''
    Flavor_Text = ''
    
    
class Core:
    Name = ''
    Type = ''
    Price = ''
    Weight = ''
    Energy_Drain = ''
    Armor_Points = ''
    Shell_Defense = ''
    Energy_Defense = ''
    Max_Weight = ''
    Anti_Missile_Reponse = ''	
    Anti_Missile_Angle = ''	
    Extension_Slots = ''
    Flavor_Text = ''

class Arm:
    Name = ''
    Type = ''
    Price = ''
    Weight = ''
    Energy_Drain = ''
    Armor_Points = ''
    Shell_Defense = ''
    Energy_Defense = ''
    Flavor_Text = ''
    
class Leg:
    Name = ''
    Type = ''
    Price = ''
    Weight = ''
    Energy_Drain = ''
    Armor_Points = ''
    Shell_Defense = ''
    Energy_Defense = ''
    Max = ''
    Speed = ''	
    Stability = ''	
    Jump_Function = ''
    Flavor_Text = ''
    
class Genertators:
    Name = ''
    Type = ''
    Price = ''
    Weight = ''
    Energy_Output = ''
    MaximumCharge = ''
    RedZone = ''
    Flavor_Text = ''
    
class FCS:
    Name = ''
    Type = ''
    Price = ''
    Weight = ''
    Energy_Drain = ''
    MaximumLock = ''
    Lock = ''
    Flavor_Text = ''
    
class Booster:
    Name = ''
    Type = ''
    Price = ''
    Weight = ''
    Energy_Drain = ''
    Boost_Power = ''
    Charge_Drain = ''
    Flavor_Text = ''